In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('../data/raw/flights.csv')

In [24]:
df.head()

,id,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,name
0,0,2013,1,1,517.0,515,2.0,830.0,819,11.0,...,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00,United Air Lines Inc.
1,1,2013,1,1,533.0,529,4.0,850.0,830,20.0,...,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00,United Air Lines Inc.
2,2,2013,1,1,542.0,540,2.0,923.0,850,33.0,...,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00,American Airlines Inc.
3,3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,...,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00,JetBlue Airways
4,4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,...,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00,Delta Air Lines Inc.

In [25]:
df.sample(30)

,id,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,name
224239,224239,2013,6,3,1203.0,1212,-9.0,1413.0,1439,-26.0,...,1734,N87507,EWR,PHX,288.0,2133,12,12,2013-06-03 12:00:00,United Air Lines Inc.
299589,299589,2013,8,21,1512.0,1511,1.0,1724.0,1728,-4.0,...,745,N558UA,LGA,DEN,209.0,1620,15,11,2013-08-21 15:00:00,United Air Lines Inc.
181730,181730,2013,4,18,1437.0,1436,1.0,1752.0,1755,-3.0,...,595,N596UA,JFK,SFO,325.0,2586,14,36,2013-04-18 14:00:00,United Air Lines Inc.
36230,36230,2013,10,10,1834.0,1830,4.0,2122.0,2122,0.0,...,153,N655JB,JFK,PBI,139.0,1028,18,30,2013-10-10 18:00:00,JetBlue Airways
213285,213285,2013,5,22,1045.0,920,85.0,NaN,1225,NaN,...,1739,N584AA,EWR,DFW,NaN,1372,9,20,2013-05-22 09:00:00,American Airlines Inc.
200877,200877,2013,5,8,NaN,835,NaN,NaN,1020,NaN,...,4558,N720MQ,LGA,CLE,NaN,419,8,35,2013-05-08 08:00:00,Envoy Air
4396,4396,2013,1,6,716.0,720,-4.0,858.0,926,-28.0,...,731,N357NB,LGA,DTW,88.0,502,7,20,2013-01-06 07:00:00,Delta Air Lines Inc.
46844,46844,2013,10,22,1021.0,1025,-4.0,1245.0,1258,-13.0,...,1529,N381DN,JFK,LAS,302.0,2248,10,25,2013-10-22 10:00:00,Delta Air Lines Inc.
93922,93922,2013,12,12,1359.0,1345,14.0,1711.0,1656,15.0,...,1779,N902DE,LGA,FLL,153.0,1076,13,45,2013-12-12 13:00:00,Delta Air Lines Inc.
64736,64736,2013,11,10,1751.0,1800,-9.0,1945.0,2002,-17.0,...,4382,N15910,EWR,DTW,92.0,488,18,0,2013-11-10 18:00:00,ExpressJet Airlines Inc.
273902,273902,2013,7,25,1837.0,1759,38.0,2203.0,2058,65.0,...,535,N595UA,JFK,LAX,319.0,2475,17,59,2013-07-25 17:00:00,United Air Lines Inc.
69180,69180,2013,11,15,954.0,958,-4.0,1151.0,1215,-24.0,...,4060,N8943A,LGA,DAY,89.0,549,9,58,2013-11-15 09:00:00,Endeavor Air Inc.
186795,186795,2013,4,23,2220.0,2025,115.0,102.0,2333,89.0,...,1241,N78501,EWR,TPA,136.0,997,20,25,2013-04-23 20:00:00,United Air Lines Inc.
145307,145307,2013,3,10,1955.0,1951,4.0,2255.0,2329,-34.0,...,91,N566JB,JFK,OAK,329.0,2576,19,51,2013-03-10 19:00:00,JetBlue Airways
19528,19528,2013,1,23,1317.0,1320,-3.0,1640.0,1650,-10.0,...,411,N632VA,JFK,LAX,358.0,2475,13,20,2013-01-23 13:00:00,Virgin America
186421,186421,2013,4,23,1519.0,1530,-11.0,1843.0,1839,4.0,...,3325,N932XJ,JFK,DFW,206.0,1391,15,30,2013-04-23 15:00:00,Endeavor Air Inc.
280414,280414,2013,8,1,1518.0,1520,-2.0,1757.0,1754,3.0,...,646,N504UA,EWR,IAH,181.0,1400,15,20,2013-08-01 15:00:00,United Air Lines Inc.
180079,180079,2013,4,16,1925.0,1924,1.0,2034.0,2055,-21.0,...,1703,N77261,EWR,BOS,43.0,200,19,24,2013-04-16 19:00:00,United Air Lines Inc.
165429,165429,2013,4,1,1123.0,1020,63.0,1421.0,1330,51.0,...,731,N519AA,LGA,DFW,211.0,1389,10,20,2013-04-01 10:00:00,American Airlines Inc.
271888,271888,2013,7,23,1958.0,1729,149.0,2113.0,1855,138.0,...,4224,N11548,EWR,MKE,115.0,725,17,29,2013-07-23 17:00:00,ExpressJet Airlines Inc.
161380,161380,2013,3,27,2020.0,2024,-4.0,2332.0,2340,-8.0,...,1069,N178JB,JFK,AUS,211.0,1521,20,24,2013-03-27 20:00:00,JetBlue Airways
233869,233869,2013,6,13,1510.0,1455,15.0,1638.0,1630,8.0,...,1164,N346NB,JFK,BOS,41.0,187,14,55,2013-06-13 14:00:00,Delta Air Lines Inc.
95542,95542,2013,12,14,847.0,850,-3.0,1101.0,1055,6.0,...,3478,N539MQ,LGA,DTW,91.0,502,8,50,2013-12-14 08:00:00,Envoy Air
220058,220058,2013,5,29,1858.0,1855,3.0,2213.0,2146,27.0,...,195,N630JB,JFK,LAS,325.0,2248,18,55,2013-05-29 18:00:00,JetBlue Airways
25295,25295,2013,1,30,743.0,745,-2.0,1214.0,1234,-20.0,...,1481,N57869,EWR,SJU,187.0,1608,7,45,2013-01-30 07:00:00,United Air Lines Inc.
249926,249926,2013,6,30,1336.0,1340,-4.0,1639.0,1700,-21.0,...,1073,N3HGAA,LGA,MIA,156.0,1096,13,40,2013-06-30 13:00:00,American Airlines Inc.
180103,180103,2013,4,16,1949.0,1710,159.0,2137.0,1915,142.0,...,1351,N3ANAA,JFK,ORD,129.0,740,17,10,2013-04-16 17:00:00,American Airlines Inc.
217749,217749,2013,5,27,1312.0,1318,-6.0,1606.0,1619,-13.0,...,1584,N26123,EWR,LAX,324.0,2454,13,18,2013-05-27 13:00:00,United Air Lines Inc.
98035,98035,2013,12,17,731.0,700,31.0,931.0,809,82.0,...,2169,N702UW,LGA,DCA,53.0,214,7,0,2013-12-17 07:00:00,US Airways Inc.
22585,22585,2013,1,27,702.0,653,9.0,956.0,937,19.0,...,1506,N53441,EWR,LAS,334.0,2227,6,53,2013-01-27 06:00:00,United Air Lines Inc.

In [26]:
df.describe()

,id,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,flight,air_time,distance,hour,minute
count,336776.000000,336776.0,336776.000000,336776.000000,328521.000000,336776.000000,328521.000000,328063.000000,336776.000000,327346.000000,336776.000000,327346.000000,336776.000000,336776.000000,336776.000000
mean,168387.500000,2013.0,6.548510,15.710787,1349.109947,1344.254840,12.639070,1502.054999,1536.380220,6.895377,1971.923620,150.686460,1039.912604,13.180247,26.230100
std,97219.001466,0.0,3.414457,8.768607,488.281791,467.335756,40.210061,533.264132,497.457142,44.633292,1632.471938,93.688305,733.233033,4.661316,19.300846
min,0.000000,2013.0,1.000000,1.000000,1.000000,106.000000,-43.000000,1.000000,1.000000,-86.000000,1.000000,20.000000,17.000000,1.000000,0.000000
25%,84193.750000,2013.0,4.000000,8.000000,907.000000,906.000000,-5.000000,1104.000000,1124.000000,-17.000000,553.000000,82.000000,502.000000,9.000000,8.000000
50%,168387.500000,2013.0,7.000000,16.000000,1401.000000,1359.000000,-2.000000,1535.000000,1556.000000,-5.000000,1496.000000,129.000000,872.000000,13.000000,29.000000
75%,252581.250000,2013.0,10.000000,23.000000,1744.000000,1729.000000,11.000000,1940.000000,1945.000000,14.000000,3465.000000,192.000000,1389.000000,17.000000,44.000000
max,336775.000000,2013.0,12.000000,31.000000,2400.000000,2359.000000,1301.000000,2400.000000,2359.000000,1272.000000,8500.000000,695.000000,4983.000000,23.000000,59.000000

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              336776 non-null  int64
 1   year            336776 non-null  int64
 2   month           336776 non-null  int64
 3   day             336776 non-null  int64
 4   dep_time        328521 non-null  float64
 5   sched_dep_time  336776 non-null  int64
 6   dep_delay       328521 non-null  float64
 7   arr_time        328063 non-null  float64
 8   sched_arr_time  336776 non-null  int64
 9   arr_delay       327346 non-null  float64
 10  carrier         336776 non-null  str
 11  flight          336776 non-null  int64
 12  tailnum         334264 non-null  str
 13  origin          336776 non-null  str
 14  dest            336776 non-null  str
 15  air_time        327346 non-null  float64
 16  distance        336776 non-null  int64
 17  hour            336776 non-null  int64
 18  minute          336776 non-null  int64
 19  time_hour       336776 non-null  str
 20  name            336776 non-null  str
dtypes: float64(5), int64(10), str(6)
memory usage: 54.0 MB

In [28]:
df.shape

(336776, 21)

In [29]:
df.isna().sum()

id                   0
year                 0
month                0
day                  0
dep_time          8255
sched_dep_time       0
dep_delay         8255
arr_time          8713
sched_arr_time       0
arr_delay         9430
carrier              0
flight               0
tailnum           2512
origin               0
dest                 0
air_time          9430
distance             0
hour                 0
minute               0
time_hour            0
name                 0
dtype: int64

In [30]:
df.columns.tolist()

['id',
 'year',
 'month',
 'day',
 'dep_time',
 'sched_dep_time',
 'dep_delay',
 'arr_time',
 'sched_arr_time',
 'arr_delay',
 'carrier',
 'flight',
 'tailnum',
 'origin',
 'dest',
 'air_time',
 'distance',
 'hour',
 'minute',
 'time_hour',
 'name']

In [31]:
df['year'].unique()

array([2013])

In [32]:
df['carrier'].unique()

<StringArray>
['UA', 'AA', 'B6', 'DL', 'EV', 'MQ', 'US', 'WN', 'VX', 'FL', 'AS', '9E', 'F9',
 'HA', 'YV', 'OO']
Length: 16, dtype: str

In [33]:
df['name'].unique()

<StringArray>
[      'United Air Lines Inc.',      'American Airlines Inc.',
             'JetBlue Airways',        'Delta Air Lines Inc.',
    'ExpressJet Airlines Inc.',                   'Envoy Air',
             'US Airways Inc.',      'Southwest Airlines Co.',
              'Virgin America', 'AirTran Airways Corporation',
        'Alaska Airlines Inc.',           'Endeavor Air Inc.',
      'Frontier Airlines Inc.',      'Hawaiian Airlines Inc.',
          'Mesa Airlines Inc.',       'SkyWest Airlines Inc.']
Length: 16, dtype: str

In [34]:
df['name'].value_counts()

name
United Air Lines Inc.          58665
JetBlue Airways                54635
ExpressJet Airlines Inc.       54173
Delta Air Lines Inc.           48110
American Airlines Inc.         32729
Envoy Air                      26397
US Airways Inc.                20536
Endeavor Air Inc.              18460
Southwest Airlines Co.         12275
Virgin America                  5162
AirTran Airways Corporation     3260
Alaska Airlines Inc.             714
Frontier Airlines Inc.           685
Mesa Airlines Inc.               601
Hawaiian Airlines Inc.           342
SkyWest Airlines Inc.             32
Name: count, dtype: int64

In [35]:
df['name'].isna().sum()

np.int64(0)

In [36]:
df.duplicated().sum()

np.int64(0)