In [20]:
import pandas as pd
from clean import format_time

ModuleNotFoundError: No module named 'clean'

In [ ]:
df = pd.read_csv('../data/raw/flights.csv')

In [ ]:
df['name'] = df['name'].str.capitalize().str.strip()
df['name'].unique().tolist()

['United air lines inc.',
 'American airlines inc.',
 'Jetblue airways',
 'Delta air lines inc.',
 'Expressjet airlines inc.',
 'Envoy air',
 'Us airways inc.',
 'Southwest airlines co.',
 'Virgin america',
 'Airtran airways corporation',
 'Alaska airlines inc.',
 'Endeavor air inc.',
 'Frontier airlines inc.',
 'Hawaiian airlines inc.',
 'Mesa airlines inc.',
 'Skywest airlines inc.']

In [ ]:
df['name'] = df['name'].str.replace(r'\bco\.?\b','',regex= True)
df['name'] = df['name'].str.replace(r'\binc\.?\b', '', regex=True)
df['name'] = df['name'].str.replace(r'\bcorporation\.?\b','',regex=True)
df['name'] = df['name'].str.replace(r'\.$', '', regex=True)
df['name'] = df['name'].str.replace(r'air\s+lines', 'airlines', regex=True)
df['name'] = df['name'].str.replace(r'\bair\b','airlines',regex=True)
df['name'] = df['name'].replace('Virgin america', 'virgin america airlines')
df['name'] = df['name'].str.strip()
df['name'].unique().tolist()

['United airlines',
 'American airlines',
 'Jetblue airways',
 'Delta airlines',
 'Expressjet airlines',
 'Envoy airlines',
 'Us airways',
 'Southwest airlines',
 'virgin america airlines',
 'Airtran airways',
 'Alaska airlines',
 'Endeavor airlines',
 'Frontier airlines',
 'Hawaiian airlines',
 'Mesa airlines',
 'Skywest airlines']

In [ ]:
df['is_cancalled'] = df['dep_time'].isna().astype(int)

In [ ]:
df['dep_time_format'] = df['dep_time'].apply(format_time)
df[["dep_time_format","dep_time"]].head()

  dep_time_format  dep_time
0           05:17     517.0
1           05:33     533.0
2           05:42     542.0
3           05:44     544.0
4           05:54     554.0

In [ ]:
df['arr_time_format'] = df['arr_time'].apply(format_time)

In [ ]:
df['sched_arr_time_formatted']= df['sched_arr_time'].apply(format_time)

In [ ]:
df['sched_dep_time_formatted'] = df['sched_dep_time'].apply(format_time)

In [ ]:
df['flight_date'] = pd.to_datetime(df[['year','month','day','hour', 'minute']])
df

,id,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,distance,hour,minute,time_hour,name,flight_date,dep_time_format,arr_time_format,sched_dep_time_formatted,sched_arr_time_formatted
0,0,2013,1,1,517.0,515,2.0,830.0,819,11.0,...,1400,5,15,2013-01-01 05:00:00,United airlines,2013-01-01 05:15:00,05:17,08:30,05:15,08:19
1,1,2013,1,1,533.0,529,4.0,850.0,830,20.0,...,1416,5,29,2013-01-01 05:00:00,United airlines,2013-01-01 05:29:00,05:33,08:50,05:29,08:30
2,2,2013,1,1,542.0,540,2.0,923.0,850,33.0,...,1089,5,40,2013-01-01 05:00:00,American airlines,2013-01-01 05:40:00,05:42,09:23,05:40,08:50
3,3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,...,1576,5,45,2013-01-01 05:00:00,Jetblue airways,2013-01-01 05:45:00,05:44,10:04,05:45,10:22
4,4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,...,762,6,0,2013-01-01 06:00:00,Delta airlines,2013-01-01 06:00:00,05:54,08:12,06:00,08:37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,...,213,14,55,2013-09-30 14:00:00,Endeavor airlines,2013-09-30 14:55:00,00:00,00:00,14:55,16:34
336772,336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,...,198,22,0,2013-09-30 22:00:00,Endeavor airlines,2013-09-30 22:00:00,00:00,00:00,22:00,23:12
336773,336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,...,764,12,10,2013-09-30 12:00:00,Envoy airlines,2013-09-30 12:10:00,00:00,00:00,12:10,13:30
336774,336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,...,419,11,59,2013-09-30 11:00:00,Envoy airlines,2013-09-30 11:59:00,00:00,00:00,11:59,13:44
336775,336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,...,431,8,40,2013-09-30 08:00:00,Envoy airlines,2013-09-30 08:40:00,00:00,00:00,08:40,10:20

In [21]:
df['dep_time'] = pd.to_datetime(df['dep_time_format'], format='%H:%M').dt.time

In [24]:
df['sched_dep_time'] = pd.to_datetime(df['sched_dep_time_formatted'], format='%H:%M').dt.time

In [25]:
df

,id,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,hour,minute,time_hour,name,flight_date,dep_time_format,arr_time_format,sched_dep_time_formatted,sched_arr_time_formatted,is_cancalled
0,0,2013,1,1,05:17:00,05:15:00,2.0,830.0,819,11.0,...,5,15,2013-01-01 05:00:00,United airlines,2013-01-01 05:15:00,05:17,08:30,05:15,08:19,0
1,1,2013,1,1,05:33:00,05:29:00,4.0,850.0,830,20.0,...,5,29,2013-01-01 05:00:00,United airlines,2013-01-01 05:29:00,05:33,08:50,05:29,08:30,0
2,2,2013,1,1,05:42:00,05:40:00,2.0,923.0,850,33.0,...,5,40,2013-01-01 05:00:00,American airlines,2013-01-01 05:40:00,05:42,09:23,05:40,08:50,0
3,3,2013,1,1,05:44:00,05:45:00,-1.0,1004.0,1022,-18.0,...,5,45,2013-01-01 05:00:00,Jetblue airways,2013-01-01 05:45:00,05:44,10:04,05:45,10:22,0
4,4,2013,1,1,05:54:00,06:00:00,-6.0,812.0,837,-25.0,...,6,0,2013-01-01 06:00:00,Delta airlines,2013-01-01 06:00:00,05:54,08:12,06:00,08:37,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,336771,2013,9,30,00:00:00,14:55:00,NaN,NaN,1634,NaN,...,14,55,2013-09-30 14:00:00,Endeavor airlines,2013-09-30 14:55:00,00:00,00:00,14:55,16:34,1
336772,336772,2013,9,30,00:00:00,22:00:00,NaN,NaN,2312,NaN,...,22,0,2013-09-30 22:00:00,Endeavor airlines,2013-09-30 22:00:00,00:00,00:00,22:00,23:12,1
336773,336773,2013,9,30,00:00:00,12:10:00,NaN,NaN,1330,NaN,...,12,10,2013-09-30 12:00:00,Envoy airlines,2013-09-30 12:10:00,00:00,00:00,12:10,13:30,1
336774,336774,2013,9,30,00:00:00,11:59:00,NaN,NaN,1344,NaN,...,11,59,2013-09-30 11:00:00,Envoy airlines,2013-09-30 11:59:00,00:00,00:00,11:59,13:44,1
336775,336775,2013,9,30,00:00:00,08:40:00,NaN,NaN,1020,NaN,...,8,40,2013-09-30 08:00:00,Envoy airlines,2013-09-30 08:40:00,00:00,00:00,08:40,10:20,1

In [ ]:
df['sched_arr_time'].info()

<class 'pandas.Series'>
RangeIndex: 336776 entries, 0 to 336775
Series name: sched_arr_time
Non-Null Count   Dtype
--------------   -----
336776 non-null  int64
dtypes: int64(1)
memory usage: 2.6 MB